/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

export interface GameTemplate {
  id: string;
  title: string;
  subtitle: string;
  description: string;
  difficulty: 'Casual' | 'Easy' | 'Medium' | 'Hard' | 'Expert' | 'Legendary';
  difficultyColor: string;
  themeIcon: string;
  badge: string;
  bgGradient: string;
  cardBorder: string;
  glowColor: string;
  accentColor: string;
  themeEnv: 'classic' | 'jungle' | 'temple' | 'galaxy' | 'ice' | 'volcano' | 'fantasy' | 'egypt' | 'forest' | 'adventure';
  layoutType: 'classic_wall' | 'circle' | 'spiral' | 'diamond' | 'snake' | 'hexagon' | 'double_ring' | 'maze' | 'cross' | 'wave' | 'star';
  layoutName: string;
  defaultLauncher: string;
  defaultBall: string;
  colorPalette: string[];
  multiplierBonus: number;
  bgCanvasStyle: string;
}

export const GAME_TEMPLATES: GameTemplate[] = [
  {
    id: 'classic_bubble',
    title: 'Classic Bubble Shooter',
    subtitle: 'Original Arcade Edition',
    description: 'Timeless arcade marble popping featuring precision trajectory aiming, satisfying chain reaction pops, and classic colorful spheres.',
    difficulty: 'Easy',
    difficultyColor: '#22c55e',
    themeIcon: '🔮',
    badge: 'POPULAR',
    bgGradient: 'from-blue-950 via-slate-900 to-black',
    cardBorder: 'border-blue-500/30 hover:border-blue-400',
    glowColor: 'rgba(59, 130, 246, 0.4)',
    accentColor: '#3b82f6',
    themeEnv: 'classic',
    layoutType: 'classic_wall',
    layoutName: 'Classic Grid',
    defaultLauncher: 'classic_cannon',
    defaultBall: 'classic_ball',
    colorPalette: ['#ef4444', '#facc15', '#3b82f6', '#10b981', '#a855f7'],
    multiplierBonus: 1.0,
    bgCanvasStyle: '#020617',
  },
  {
    id: 'jungle_rescue',
    title: 'Jungle Bird Rescue',
    subtitle: 'Rainforest Canopy Rescue',
    description: 'Rescue trapped baby birds trapped inside golden star bubble clusters surrounded by ancient rainforest vines and obstacles.',
    difficulty: 'Medium',
    difficultyColor: '#3b82f6',
    themeIcon: '🦜',
    badge: 'RESCUE',
    bgGradient: 'from-emerald-950 via-zinc-900 to-black',
    cardBorder: 'border-emerald-500/30 hover:border-emerald-400',
    glowColor: 'rgba(16, 185, 129, 0.4)',
    accentColor: '#10b981',
    themeEnv: 'jungle',
    layoutType: 'star',
    layoutName: 'Rescue Star',
    defaultLauncher: 'dragon_launcher',
    defaultBall: 'crystal_ball',
    colorPalette: ['#10b981', '#facc15', '#ef4444', '#38bdf8', '#8b5cf6'],
    multiplierBonus: 1.35,
    bgCanvasStyle: '#022c22',
  },
  {
    id: 'spiral_temple',
    title: 'Spiral Temple',
    subtitle: 'Sacred Emerald Ruins',
    description: 'Sacred stone ruins guarded by glowing emerald runes, spiral path marble traps, and hidden treasure scarabs.',
    difficulty: 'Hard',
    difficultyColor: '#f97316',
    themeIcon: '🏛️',
    badge: 'LEGENDARY',
    bgGradient: 'from-teal-950 via-slate-900 to-black',
    cardBorder: 'border-teal-500/30 hover:border-teal-400',
    glowColor: 'rgba(20, 184, 166, 0.4)',
    accentColor: '#14b8a6',
    themeEnv: 'temple',
    layoutType: 'spiral',
    layoutName: 'Spiral Path',
    defaultLauncher: 'cobra_launcher',
    defaultBall: 'plasma_ball',
    colorPalette: ['#14b8a6', '#eab308', '#ec4899', '#3b82f6', '#f97316'],
    multiplierBonus: 1.5,
    bgCanvasStyle: '#042f2e',
  },
  {
    id: 'dragon_maze',
    title: 'Dragon Maze',
    subtitle: 'Lair of the Flame Dragon',
    description: 'Wind through narrow cavern walls and stone obstacles to reach the fiery dragon orb in the maze center.',
    difficulty: 'Hard',
    difficultyColor: '#f97316',
    themeIcon: '🐉',
    badge: 'BOSS',
    bgGradient: 'from-red-950 via-zinc-950 to-black',
    cardBorder: 'border-red-500/30 hover:border-red-400',
    glowColor: 'rgba(239, 68, 68, 0.4)',
    accentColor: '#ef4444',
    themeEnv: 'volcano',
    layoutType: 'maze',
    layoutName: 'Cavern Maze',
    defaultLauncher: 'dragon_launcher',
    defaultBall: 'fire_ball',
    colorPalette: ['#ef4444', '#f97316', '#facc15', '#38bdf8', '#c084fc'],
    multiplierBonus: 1.6,
    bgCanvasStyle: '#1f0404',
  },
  {
    id: 'crystal_rings',
    title: 'Crystal Rings',
    subtitle: 'Prismatic Floating Islands',
    description: 'Concentric double rings of glowing crystals floating over a glass sanctuary with high combo multipliers.',
    difficulty: 'Medium',
    difficultyColor: '#3b82f6',
    themeIcon: '💎',
    badge: 'FEATURED',
    bgGradient: 'from-cyan-950 via-slate-900 to-black',
    cardBorder: 'border-cyan-500/30 hover:border-cyan-400',
    glowColor: 'rgba(6, 182, 212, 0.4)',
    accentColor: '#06b6d4',
    themeEnv: 'ice',
    layoutType: 'double_ring',
    layoutName: 'Double Ring',
    defaultLauncher: 'crystal_dragon',
    defaultBall: 'ice_ball',
    colorPalette: ['#38bdf8', '#a5f3fc', '#f472b6', '#facc15', '#a78bfa'],
    multiplierBonus: 1.4,
    bgCanvasStyle: '#083344',
  },
  {
    id: 'galaxy_orbit',
    title: 'Galaxy Orbit',
    subtitle: 'Starlight Cosmic Nebula',
    description: 'Zero-gravity space battle shooting dark matter spheres across starlight nebulae and orbiting circular galactic rings.',
    difficulty: 'Expert',
    difficultyColor: '#a855f7',
    themeIcon: '🌌',
    badge: 'EXCLUSIVE',
    bgGradient: 'from-purple-950 via-indigo-950 to-black',
    cardBorder: 'border-purple-500/30 hover:border-purple-400',
    glowColor: 'rgba(168, 85, 247, 0.4)',
    accentColor: '#a855f7',
    themeEnv: 'galaxy',
    layoutType: 'circle',
    layoutName: 'Circular Orbit',
    defaultLauncher: 'mechanical_cannon',
    defaultBall: 'mythic_orb',
    colorPalette: ['#c084fc', '#38bdf8', '#f472b6', '#facc15', '#34d399'],
    multiplierBonus: 1.8,
    bgCanvasStyle: '#0f0728',
  },
  {
    id: 'snake_tunnel',
    title: 'Snake Tunnel',
    subtitle: 'Wilderness Speed Trail',
    description: 'Fast-paced marble shooting quest with speed surges, double combo multipliers, and serpentine obstacle curves.',
    difficulty: 'Medium',
    difficultyColor: '#3b82f6',
    themeIcon: '🐍',
    badge: 'SPEED',
    bgGradient: 'from-amber-950 via-zinc-900 to-black',
    cardBorder: 'border-amber-500/30 hover:border-amber-400',
    glowColor: 'rgba(245, 158, 11, 0.4)',
    accentColor: '#f59e0b',
    themeEnv: 'adventure',
    layoutType: 'snake',
    layoutName: 'Serpentine Trail',
    defaultLauncher: 'cobra_launcher',
    defaultBall: 'gold_ball',
    colorPalette: ['#f97316', '#eab308', '#22c55e', '#06b6d4', '#ec4899'],
    multiplierBonus: 1.25,
    bgCanvasStyle: '#0f172a',
  },
  {
    id: 'infinity_loop',
    title: 'Infinity Loop',
    subtitle: 'Chrono Time Warp',
    description: 'Twisting figure-eight marble loop with reversing time bubbles and plasma wave explosions.',
    difficulty: 'Hard',
    difficultyColor: '#f97316',
    themeIcon: '♾️',
    badge: 'WARP',
    bgGradient: 'from-indigo-950 via-slate-900 to-black',
    cardBorder: 'border-indigo-500/30 hover:border-indigo-400',
    glowColor: 'rgba(99, 102, 241, 0.4)',
    accentColor: '#6366f1',
    themeEnv: 'fantasy',
    layoutType: 'wave',
    layoutName: 'Wave Loop',
    defaultLauncher: 'eagle_launcher',
    defaultBall: 'plasma_ball',
    colorPalette: ['#818cf8', '#c084fc', '#f472b6', '#38bdf8', '#34d399'],
    multiplierBonus: 1.45,
    bgCanvasStyle: '#111827',
  },
  {
    id: 'diamond_castle',
    title: 'Diamond Castle',
    subtitle: 'Royal Diamond Fortress',
    description: 'Intricate rhombus diamond shield formation guarding royal treasure chests and golden coins.',
    difficulty: 'Medium',
    difficultyColor: '#3b82f6',
    themeIcon: '♦️',
    badge: 'ROYAL',
    bgGradient: 'from-sky-950 via-zinc-900 to-black',
    cardBorder: 'border-sky-500/30 hover:border-sky-400',
    glowColor: 'rgba(14, 165, 233, 0.4)',
    accentColor: '#0ea5e9',
    themeEnv: 'classic',
    layoutType: 'diamond',
    layoutName: 'Diamond Rhombus',
    defaultLauncher: 'lion_launcher',
    defaultBall: 'royal_ball',
    colorPalette: ['#38bdf8', '#facc15', '#f472b6', '#34d399', '#a78bfa'],
    multiplierBonus: 1.3,
    bgCanvasStyle: '#0c4a6e',
  },
  {
    id: 'ancient_pyramid',
    title: 'Ancient Pyramid',
    subtitle: "Pharaoh's Gold Tomb",
    description: "Pharaoh's secret tomb guarded by golden scarabs, pyramid triangle clusters, and 2.0x multiplier rewards.",
    difficulty: 'Legendary',
    difficultyColor: '#eab308',
    themeIcon: '🛕',
    badge: 'MYTHIC',
    bgGradient: 'from-yellow-950 via-amber-950 to-black',
    cardBorder: 'border-amber-400/50 hover:border-yellow-300',
    glowColor: 'rgba(234, 179, 8, 0.5)',
    accentColor: '#eab308',
    themeEnv: 'egypt',
    layoutType: 'hexagon',
    layoutName: 'Pyramid Hexagon',
    defaultLauncher: 'royal_cannon',
    defaultBall: 'gold_ball',
    colorPalette: ['#facc15', '#38bdf8', '#ef4444', '#10b981', '#a855f7'],
    multiplierBonus: 2.0,
    bgCanvasStyle: '#1c1305',
  },
  {
    id: 'ocean_kingdom',
    title: 'Ocean Kingdom',
    subtitle: 'Sunken Atlantis Reef',
    description: 'Deep sea coral reef with hydrodynamic bubbles, shark jaw cannons, and tidal wave pops.',
    difficulty: 'Easy',
    difficultyColor: '#22c55e',
    themeIcon: '🦈',
    badge: 'AQUA',
    bgGradient: 'from-blue-950 via-cyan-950 to-black',
    cardBorder: 'border-blue-500/30 hover:border-blue-400',
    glowColor: 'rgba(59, 130, 246, 0.4)',
    accentColor: '#2563eb',
    themeEnv: 'classic',
    layoutType: 'cross',
    layoutName: 'Ocean Cross',
    defaultLauncher: 'shark_launcher',
    defaultBall: 'crystal_ball',
    colorPalette: ['#3b82f6', '#06b6d4', '#60a5fa', '#facc15', '#a78bfa'],
    multiplierBonus: 1.2,
    bgCanvasStyle: '#172554',
  },
  {
    id: 'volcano_route',
    title: 'Volcano Route',
    subtitle: 'Molten Lava Caverns',
    description: 'High-intensity molten lava caverns with explosive magma fireballs and cruciform cross targets.',
    difficulty: 'Hard',
    difficultyColor: '#f97316',
    themeIcon: '🌋',
    badge: 'EXTREME',
    bgGradient: 'from-orange-950 via-zinc-950 to-black',
    cardBorder: 'border-orange-500/30 hover:border-orange-400',
    glowColor: 'rgba(249, 115, 22, 0.4)',
    accentColor: '#f97316',
    themeEnv: 'volcano',
    layoutType: 'cross',
    layoutName: 'Lava Cross',
    defaultLauncher: 'phoenix_launcher',
    defaultBall: 'fire_ball',
    colorPalette: ['#ef4444', '#f97316', '#facc15', '#38bdf8', '#c084fc'],
    multiplierBonus: 1.65,
    bgCanvasStyle: '#2a0a03',
  },
];

export const PLAY_STORE_CATEGORY_TAGS = [
  { name: 'Casual', icon: '🎮' },
  { name: 'Puzzle', icon: '🧩' },
  { name: 'Bubble Shooter', icon: '🔮' },
  { name: 'Marble Shooter', icon: '🦎' },
  { name: 'Offline', icon: '⚡' },
  { name: 'Single Player', icon: '👤' },
  { name: 'Adventure', icon: '🧭' },
  { name: 'Arcade', icon: '🕹️' },
  { name: 'Strategy', icon: '🎯' },
  { name: 'Color Match', icon: '🎨' },
  { name: 'Family', icon: '👨‍👩‍👧' },
  { name: 'Relaxing', icon: '🍃' },
  { name: 'Skill Based', icon: '🏆' },
  { name: 'Quick Play', icon: '⏱️' },
  { name: 'Challenge', icon: '🔥' },
];
